---
- name: "Include {{ ansible_distribution }}-specific variables"
  include_vars: "{{ ansible_distribution }}.yml"

- name: Include FTSConfig variables
  include_vars: "FTSConfig.yml"

- name: Get public IPv4
  uri:
    url: http://ifconfig.me/ip
    return_content: true
  register: ip_response

- name: Set public IPv4
  set_fact:
    fts_public_ipv4: "{{ ip_response.content }}"

- name: Print IPv4
  debug:
    msg: "fts_public_ipv4 = {{ fts_public_ipv4 }}"

- name: Set localhost IPv4
  set_fact:
    fts_ipv4: 127.0.0.1

- name: Check if fts_version is not defined
  block:
    - name: Get the latest freetakserver version
      shell: pip show freetakserver | grep Version | cut -d ' ' -f 2
      register: pip_output

    - name: Set fts_version
      set_fact:
        fts_version: "{{ pip_output.stdout }}"
  when: fts_version is undefined or fts_version == ''

- name: Setup
  include_tasks: "setup-{{ ansible_distribution }}.yml"

- name: Configure
  include_tasks: "configure-{{ ansible_distribution }}.yml"
