---
- name: Delete PyYAML
  shell: "{{ item }}"
  loop:
    - "rm -rf /usr/lib/python3/dist-packages/yaml"
    - "rm -rf /usr/lib/python3/dist-packages/PyYAML-*"
    - "rm -rf /usr/lib/python{{ python3_version }}/site-packages/PyYAML-*"

- name: Install apt dependencies
  apt:
    name: "{{ fts_apt_dependencies | list }}"

# - name: "Install {{ fts_pip_package_name }} from local source"
#   shell: /root/FreeTAKHub-Installation/scripts/install_fts_from_source.sh {{ itype }}
    
- name: "Install {{ fts_pip_package_name }}"
  pip:
    name: "{{ fts_pip_package_name }}=={{ fts_version }}"
    executable: "pip3"
