---
- name: Delete PyYAML
  shell: "{{ item }}"
  loop:
    - "rm -rf /usr/lib/python3/dist-packages/yaml"
    - "rm -rf /usr/lib/python3/dist-packages/PyYAML-*"
    - "rm -rf /usr/lib/python{{ python3_version }}/site-packages/PyYAML-*"

- name: Install apt dependencies
  apt:
    name: "{{ fts_apt_dependencies | list }}"

- name: "Install {{ fts_pip_package_name }} from local source"
  bash:
    name: "{{ fts_pip_package_name }}"
    executable: "bash"
    
# - name: "Install {{ fts_pip_package_name }}"
#   pip:
#     name: "{{ fts_pip_package_name }}"
#     executable: "pip3"
