services:
  fts:
    image: freetakserver:latest
    pull_policy: build
    restart: unless-stopped
    build:
      context: .
      dockerfile: core-pypi.Dockerfile
    ports:
        # DataPackagePort
        - 8080:8080
        # CoTPort
        - 8087:8087
        # SSLCoTPort
        - 8089:8089
        # SSLDataPackagePort
        - 8443:8443
        # FederationPort
        #- 9000:9000
        # APIPort - Don't expose by default
        #- 19023:19023
    volumes:
    # Confused about the Z at the end?
    # on hosts with selinux, you will need this.
    # a Z means the volume is not shared
    # a z means the volume is shared
      - ./base-config/:/opt/fts/:rw,Z
    network_mode: "host"

  ftsui:
    image: freetakserver-ui:latest
    pull_policy: build
    build:
      context: .
      dockerfile: ui-pypi.Dockerfile
    ports:
      # Web interface port
      - 5000:5000
      # API Port - probably don't need to expose if UI and Core are on same container network
      #- 19023:19023
    volumes:
      - ./ui-config:/home/freetak/data:rw,Z
    network_mode: "host"
