services:
  fts:
    image: freetakserver:latest
    pull_policy: build
    restart: unless-stopped
    build:
      context: .
      dockerfile: core-pypi.Dockerfile
    volumes:
    # Confused about the Z at the end?
    # on hosts with selinux, you will need this.
    # a Z means the volume is not shared
    # a z means the volume is shared
      - ./base-config/:/opt/fts/:rw,Z
    network_mode: "host"

  ftsui:
    image: freetakserver-ui:latest
    pull_policy: build
    build:
      context: .
      dockerfile: ui-pypi.Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./ui-config:/home/freetak/data:rw,Z
    network_mode: "host"
