---
- name: Get RTSP Simple Server release information with GitHub API
  uri:
    url: "{{ videoserver_api_url }}"
    return_content: true
  register: videoserver_response

- name: Set facts from GitHub API release information
  set_fact:
    videoserver_download_url: "{{ videoserver_response.json.assets[videoserver_download_index].browser_download_url }}"

- name: "Download {{ videoserver_package }} to /tmp"
  get_url:
    url: "{{ videoserver_download_url }}"
    dest: "/tmp/{{ videoserver_package }}"
    owner: root
    group: root
    mode: 0755
  register: download_result
  changed_when: download_result.status == 200

- name: "Unarchive {{ videoserver_package }} to /tmp"
  unarchive:
    src: "/tmp/{{ videoserver_package }}"
    dest: /tmp
    owner: root
    group: root
    mode: 0755
    remote_src: true
  when: download_result is defined and download_result.status == 200

- name: "Copy /tmp/{{ videoserver_executable }} to {{ videoserver_executable_location }}"
  copy:
    src: "/tmp/{{ videoserver_executable }}"
    dest: "{{ videoserver_executable_location }}"
    owner: root
    group: root
    mode: 0755
    remote_src: true
