---
- name: "Include {{ ansible_distribution }}-specific variables"
  include_vars: "{{ ansible_distribution }}.yml"

- name: Install apt packages
  apt:
    name: "{{ python3_apt_packages }}"

- name: "Install pip packages"
  pip:
    name: "{{ pip3_packages }}"
    executable: pip3
    # extra_args: --force-reinstall
