---
- name: "Include {{ ansible_distribution }}-specific variables"
  include_vars: "{{ ansible_distribution }}.yml"

- name: Set IPv4
  set_fact:
    noderedserver_ipv4: 127.0.0.1

- name: Print IPv4
  debug:
    msg: "noderedserver_ipv4 = {{ noderedserver_ipv4 }}"

- name: Get public IPv4
  uri:
    url: http://ifconfig.me/ip
    return_content: true
  register: ip_response

- name: Set public IPv4
  set_fact:
    true_web_ipv4: "{{ ip_response.content }}"

- name: Install
  include_tasks: "setup-{{ ansible_distribution }}.yml"

- name: Configure
  include_tasks: "configure-{{ ansible_distribution }}.yml"

- name: Notify handlers to print at the end
  shell: ":"
  notify:
    - print nodered url
    - print nodered token
