---
# system information
fts_ipv4: 0.0.0.0

fts_pip_package_name: FreeTAKServer

fts_service_name: fts

# Set initial service state. Recommended values: `started` or `stopped`.
fts_state: started

# Enable service. Recommended values: `true` or `false`
fts_enabled: true

cfg_rpath: "core/configuration"
