---
name: ZeroTouch

"on":
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - "*"
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: ['x64']
        region: ['nyc1']
    steps:
      - name: Set up SSH key
        run: |
          echo "${{ secrets.DO_SSH_KEY }}" > private_key
          chmod 600 private_key
          echo "${{ secrets.DO_SSH_KEY_PUB }}" > public_key
          chmod 600 public_key

      - name: Set up doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}

      - name: Create a new droplet
        id: create_droplet
        run: |
          droplet_info=$(doctl compute droplet create ${{ github.repository }}-${{ github.workflow }}-${{ github.job }}-${{ github.run_id }} \
            --image ubuntu-20-04-x64 \
            --size s-1vcpu-1gb \
            --region ${{ matrix.region }} \
            --ssh-keys ${{ secrets.DO_SSH_FINGERPRINT }} \
            --format ID,PublicIPv4 \
            --no-header \
            --wait)
          echo "::set-output name=droplet_id::$(echo "$droplet_info" | awk '{print $1}')"
          echo "::set-output name=droplet_ip::$(echo "$droplet_info" | awk '{print $2}')"
      - name: Wait for SSH
        run: |
          until nc -zv ${{ steps.create_droplet.outputs.droplet_ip }} 22; do
            sleep 5
           done
      - name: Checkout the git repository
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key \
            root@${{ steps.create_droplet.outputs.droplet_ip }} "bash -s" <<- 'ENDSSH'
            # Commands to install the .deb package
            git clone https://github.com/FreeTAKTeam/FreeTAKHub-Installation.git
           ENDSSH
      - name: Install and test the software
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key \
            root@${{ steps.create_droplet.outputs.droplet_ip }} "bash -s" <<- 'ENDSSH'
            # Commands to install the .deb package
            ~/FreeTAKHub-Installation/scripts/easy_install.sh

            # Commands to test the installation
            # Replace 'my_command' with the actual command or test script
            until nc -zv ${{ steps.create_droplet.outputs.droplet_ip }} 8087; do
              sleep 5
            done
          ENDSSH

      - name: Destroy droplet
        if: always()
        run: doctl compute droplet delete -f ${{ steps.create_droplet.outputs.droplet_id }}
