---
name: ZeroTouch

"on":
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - "*"
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: ['x64']
        region: ['nyc1']
    steps:
      - name: Set up SSH key
        run: |
          echo "${{ secrets.DO_SSH_KEY }}" > private_key
          chmod 600 private_key
          echo "${{ secrets.DO_SSH_KEY_PUB }}" > public_key
          chmod 600 public_key

      - name: Set up doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}

      - name: Create a new droplet
        id: create_droplet
        run: |
          DROPLET_NAME="${{ github.workflow }}-${{ github.job }}-${{ github.run_id }}"
          DROPLET_JSON=$(doctl compute droplet create $DROPLET_NAME \
            --image ubuntu-22-04-x64 \
            --size s-1vcpu-1gb \
            --region ${{ matrix.region }} \
            --ssh-keys ${{ secrets.DO_SSH_FINGERPRINT }} \
            --format ID,PublicIPv4 \
            --no-header \
            --wait \
            --output json)
          echo "$DROPLET_JSON"
          echo "DROPLET_ID=$(echo "$DROPLET_JSON" | jq '.[].id')" >> $GITHUB_ENV
          echo "DROPLET_IP=$(echo "$DROPLET_JSON" | jq -r '.[].networks.v4[0].ip_address')" >> $GITHUB_ENV
      - name: Wait for SSH
        run: |
          until nc -zv $DROPLET_IP 22; do
            sleep 5
           done
      - name: Checkout the git repository
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key \
            root@$DROPLET_IP "bash -s" <<- 'ENDSSH'
            git clone https://github.com/FreeTAKTeam/FreeTAKHub-Installation.git
          ENDSSH
      - name: Install and test the software
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key \
            root@$DROPLET_IP "bash -s" <<- 'ENDSSH'
            # Adding sleep timer due to background apt-get updates
            sleep 600
            # Execute Zerotouch Script
            ~/FreeTAKHub-Installation/scripts/easy_install.sh
            # Test if core services sockets are available
            until nc -zv $DROPLET_IP 8087; do
              sleep 5
            done
          ENDSSH

      - name: Destroy droplet
        if: always()
        run: doctl compute droplet delete -f $DROPLET_ID
